name: Scrape latest privacy and terms

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 */2 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Fetch latest karnataka-eletricity-generation stats.
      run: |-
        curl https://kptclsldc.in/StateGen.aspx > karnataka-eletricity-generation.html
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
